config/routes.rb
Rails.application.routes.draw do
  root 'home#home'
  get '/home' => 'home#home'
  get '/about' => 'home#about'

  get '/users/:id/edit_password' => 'users#edit_password', as: :edit_password
  patch '/users/:id/edit_password' => 'users#update_password', as: :update_password
  resources :users, only: [:new, :create, :edit, :update]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :comments, dependent: :nullify
  has_many :user_posts, dependent: :nullify, source: :user
  has_many :favourites, dependent: :destroy
  has_many :posts, through: :favourites

  attr_accessor :new_password
  validates :email, presence: true, uniqueness: true,
            format: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  def full_name
    "#{first_name} #{last_name}".titleize 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Logged In.'
    else
      flash[:alert] = 'Check errors and try again.'
      render :new
    end
  end

  def edit
  end

  def update
    current_user.update user_params
    redirect_to root_path, notice: 'Account Updated.'
  end

  def edit_password
  end

  def update_password
    if diff_pass? && auth_pass? && confirmed_pass? && empty_check?
      current_user.update password: user_params[:new_password]
      redirect_to root_path, notice: 'Password Changed.'
    else
      flash[:alert] = 'Please Try Again.'
      render :edit_password
    end
  end

  private
  def empty_check?
    (user_params[:new_password] || user_params[:password_confirmation]) != '' || nil
  end

  def confirmed_pass?
    user_params[:new_password] == user_params[:password_confirmation]
  end

  def diff_pass?
    user_params[:new_password] != user_params[:password]
  end

  def auth_pass?
    current_user.authenticate(user_params[:password])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :new_password, :role)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<div>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
</div>
<div>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</div>
<div>
  <%= f.label :email %>
  <%= f.email_field :email %>
</div>
<div>
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>
<div>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>
<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User Account</h1>

<%= form_for current_user do |f| %>
<div>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
</div>
<div>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</div>
<div>
  <%= f.label :email %>
  <%= f.email_field :email %>
</div>
<div>
  <%= f.submit %>
</div>
<% end %>

<%= link_to 'Change Password', edit_password_path %>

app/views/users/edit_password.html.erb
<h1>Change Password</h1>

<%= form_for current_user, url: update_password_path do |f| %>
<div>
  <%= f.label :password, 'Old Password' %>
  <%= f.password_field :password %>
</div>
<div>
  <%= f.label :new_password, 'New Password' %>
  <%= f.password_field :new_password %>
</div>
<div>
  <%= f.label :password_confirmation, 'Password Confirmation' %>
  <%= f.password_field :password_confirmation %>
</div>
<div>
  <%= f.submit 'Change Password' %>
</div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>