config/routes.rb
Rails.application.routes.draw do
  root 'home#home'
  get '/home' => 'home#home'
  get '/about' => 'home#about'

  get '/users/:id/edit_password' => 'users#edit_password', as: :edit_password
  patch '/users/:id/edit_password' => 'users#update_password', as: :update_password
  resources :users, only: [:new, :create, :edit, :update]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
  end

end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
before_action :authenticate_user!

  def index
  end

  def createz
    @post = Post.find params[:post_id]
    fav = Favourite.new(post: @post, user: current_user)
    respond_to do |format|
      if fav.save
        format.html  { redirect_to @post, notice: 'Favourited.' }
        format.js    { render :fav_success }
      else
        format.html  { redirect_to @post, alert: "Can't be Favourited." }
        format.js    { render :fav_failure }
      end
    end
  end

  def destroy
    fav = current_user.favourites.find params[:id]
    @post = Post.find params[:post_id]
    fav.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post), notice: 'Unfavourited.' }
      format.js   { render }
    end
  end

end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/_post_fav.html.erb
<% fav = @post.fav_for(current_user) %>
<% if fav %>
  <%= link_to fa_icon("star"), post_favourite_path(@post, fav),
  method: :delete, remote: true, class: "star-fav-icon" %>
<% else %>
  <%= link_to fa_icon("star-o"), post_favourites_path(@post),
  method: :post, remote: true, class: "star-fav-icon"%>
<% end %>

app/views/favourites/destroy.js.erb
$("#post-fav").html("<%= j render 'post_fav' %>");

app/views/favourites/fav_failure.js.erb
alert("Post has already been favourited.");
window.location.reload();

app/views/favourites/fav_success.js.erb
$("#post-fav").html("<%= j render 'post_fav' %>");