config/routes.rb
Rails.application.routes.draw do
  root 'home#home'
  get '/home' => 'home#home'
  get '/about' => 'home#about'

  get '/users/:id/edit_password' => 'users#edit_password', as: :edit_password
  patch '/users/:id/edit_password' => 'users#update_password', as: :update_password
  resources :users, only: [:new, :create, :edit, :update]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">

    <nav class='navbar navbar-inverse navbar-fixed-top'>
      <div class="container-fluid">
        <div class="navbar-header">
          <i class="fa fa-meh-o"></i>
          <a class="navbar-brand" href="#">BLOGBOI</a>
        </div>
        <ul class='nav navbar-nav navbar-right'>
          <li><%= link_to 'Home', home_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'All Posts', posts_path %></li>
          <li><%= link_to 'New Post', new_post_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to current_user.full_name, edit_user_path(current_user) %></li>
            <li><%= link_to 'Logout', sessions_path, method: :delete,
            data: { confirm: 'Are you sure you want to logout?' } %></li>
          <% else %>
            <li><%= link_to 'Login', new_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_path %></li>
          <% end %>
          <li><%= form_tag(posts_path, method: 'get', id: 'search-form', class: 'navbar-form navbar-right') do %>
            <%= text_field_tag :search, params[:search], placeholder: 'Search Blog', class: 'form-control' %>
            <%= submit_tag 'Search', class: 'btn btn-default' %></li>
          <% end %>
        </ul>
      <div>
    </nav>

    <% if flash[:notice] %>
      <div class='alert alert-success'><%= flash[:notice] %></div>
    <% elsif flash[:alert] %>
      <div class='alert alert-warning'><%= flash[:alert] %></div>
    <% end %>


  <%= yield %>

  </div>
</body>
</html>